name: MixLLMProxy
version: '0.1.0.0'
author: MixLLMProxy
maintainer: MixLLMProxy
license: MIT
dependencies:
- base

library:
  source-dirs: src
  exposed-modules:
    - AppEnv
    - Common
    - DB
    - ChartJson
    - RequestEventsJson
    - Route.Aliases
    - Route.OpenAI
    - Route.UI
  dependencies:
    - base
    - scotty
    - postgresql-simple
    - lucid
    - aeson
    - aeson-pretty
    - text
    - bytestring
    - case-insensitive
    - http-client
    - http-client-tls
    - http-types
    - time
    - resource-pool
    - string-conversions
    - neat-interpolation
    - wai
    - wai-middleware-static
    - wai-extra
    - format-numbers

executables:
  app:
    source-dirs: src
    main: Main.hs
    dependencies:
      - MixLLMProxy
      - base
      - scotty
      - postgresql-simple
      - lucid
      - aeson
      - aeson-pretty
      - text
      - bytestring
      - case-insensitive
      - http-client
      - http-client-tls
      - http-types
      - time
      - resource-pool
      - string-conversions
      - neat-interpolation
      - wai
      - wai-middleware-static
      - wai-extra
      - format-numbers

tests:
  spec:
    source-dirs: test
    main: Spec.hs
    other-modules:
      - ChartJsonSpec
    dependencies:
      - base
      - MixLLMProxy
      - http-client
      - text
      - bytestring
      - async
      - warp
      - wai
      - http-types
      - network
      - aeson
      - time
      - postgresql-simple
      - vector
